### ISSUE TITLE
request.queryParams in Java example is empty after returning from signicat

### ISSUE THREAD

**Issue by devdavidkarlsson** [signicat/auth#1]
request.queryParams in Java example is empty after returning from signicat, all though the header of the post contains a SAMLResponse.

**Comment by pnyheim** [comment]
I'm not sure I understand what your problem is. The example code should work just fine. 
Can you provide more information on what exactly you are doing to get it to fail?

**Comment by devdavidkarlsson** [comment]
Update my signicat dependencies from client 3.0.2 to 4.0 in my nexus, it works better now.
